### ISSUE TITLE
Phlux.createStore() should not overwrite trigger() or addListener()

### ISSUE THREAD

**Issue by ehgoodenough** [ehgoodenough/phlux#2]

**Comment by dschalk** [comment]
My dice game is online at http://schalk.net. A discussion is at https://www.fpcomplete.com/user/dschalk/Websockets%20Game%20of%20Score. My progress in converting over to React is running at http://machinegun.ninja; the code is at https://github.com/dschalk/websockets-score.

I am glad I put off developing animated games until now. It's funny that you say 'misuse' of React when you found a perfect niche for it. The coders at Facebook apparently don't create React animated games on the job (not while the boss is looking, anyway) but you have done so quite elegantly.

I am thinking of using phlux in my Game of Score project. I see that the three issues which you raised over a month ago have not been commented upon. I don't see any problems for what I intend to do. trigger() and addListener() don't exist in the code I am writing until I run Phlux.createStore, so I am not worrying about overwriting functions that don't yet exist. I am wondering under what circumstances trigger() or addListener() would already exist when Phlux.createStore is executed. Should I be worried?

Thanks for steering me away from canvas before I start work on my first animated game.

**Comment by ehgoodenough** [comment]
Hey! Thanks for leaving a comment! It's awesome to see more interest in game development in React!

As for these issues, I mostly opened them to remind myself to fix them up later. Both `trigger()` and `addListener()` are the functions that make this a "reactive" store, so overwriting them wouldn't break your store, but it'd just make them useless for React. I want to just throw an exception if the users try to create a store that already have these "keywords" defined. :]
