### ISSUE TITLE
Support ES6 classes in React v0.13

### ISSUE THREAD

**Issue by dschalk** [ehgoodenough/phlux#4]
My app has 1,485 lines of code written in the version 0.13 es6 class style. Mixins are not supported. Phlux appeals to me so much that I am tempted to re-write my code using "React.createClass" instead of "extends React.Component". That would entail hours of work, and it makes me tired to even think about it.

There are work-arounds published on Github, but my effort to use one of them turned into a fiasco. 

I am fishing for suggestions here. Or better yet, an announcement that there will soon be a version of Phlux which does not involve a mixin.

**Comment by ehgoodenough** [comment]
Yeah, it sucks that the new version of React doesn't support mixins anymore. But in the end, it's probably for the best. Anyway, for Phlux, it isn't difficult to use our stores without the mixin. All you have to do is write the code that `connectStore` had afforded us in the mixin ([as seen here](https://github.com/ehgoodenough/phlux/blob/master/phlux.js#L49)).

``` js

var HeroStore = Phlux.createStore({
    data: {
        name: "David"
    }
})

class Hero extends React.Component {
    constructor() {
        // Initialize the state to match the store.
        this.state = {
            hero: HeroStore.data
        }

        // Add a listener so that anytime the store
        // is triggered, the state of this component
        // will be updated.
        HeroStore.addListener(function(data) {
            this.setState({
                hero: data
            })
        }.bind(this))
    }
    render() {
        return (
            <div>
                Hello {this.state.hero.name}
            </div>
        )
    }
}
```

ES6 is really cool; maybe I should make a version of Phlux with "extends" syntax. Until then, though, if this snippet of code doesn't work, leave another comment, and I'll see if I can help! :D

**Comment by dschalk** [comment]
I added the HeroStore component to my project and it worked as expected. Thank you.

By the way, there is an inconsistency in your code. I changed "Store.addListener" to "HeroStore.addListener".  Otherwise, it was just cut and paste and much to my relief, es6 and Phlux are playing nicely together. 

You made it convenient for me to keep my websockets object as a global variable. The coding community can get pretty dogmatic at times, but I think I sidestepped a lot of consternation by using "const" instead of "var", declaring "const ws = createWebSocket('/')" at the top of the file, outside of all components. Incoming message are parsed in the main component (maybe soon in a Phlux store), and any component can send messages without reference to props, refs, or state.  Eyebrows might raise, but It stands as a clean, impossible-to-clobber, globally accessible link to the Haskell server. I enjoy it. It is like an old-time TV tower standing high above the complexity of the application, and it is one more reason I am glad I didn't have to use "React.createClass".

**Comment by ehgoodenough** [comment]
Thank you so much for pointing out the issue with `Store` vs `HeroStore`. I've fixed my code to reflect the correction! I'm glad this snippet of code worked well for you. If you have any more problems, don't hesitate to open another issue here on github. Thanks!!
